.ifndef MAIN_INPUT_INC
MAIN_INPUT_INC = 1

.global mi_init
.global mi_repaint
.global mi_reset
.global mi_hide_cursor
.global mi_show_cursor
.global mi_metadata
.global mi_data
.global mi_edit_move_cursor_up
.global mi_edit_move_cursor_down
.global mi_edit_move_cursor_left
.global mi_edit_move_cursor_right
.global mi_edit_type_char
.global mi_edit_backspace
.global mi_shift_clear
.global mi_edit_line_insert
.global mi_edit_char_insert
.global mi_edit_line_delete
.global mi_edit_char_delete

.endif
