.ifndef TERM_MULTI_INPUT_INC
TERM_MULTI_INPUT_INC = 1

.global tmi_init
.global tmi_repaint
.global tmi_reset
.global tmi_hide_cursor
.global tmi_show_cursor
.global tmi_metadata
.global tmi_data
.global tmi_edit_move_cursor_up
.global tmi_edit_move_cursor_down
.global tmi_edit_move_cursor_left
.global tmi_edit_move_cursor_right
.global tmi_edit_type_char
.global tmi_edit_backspace
.global tmi_shift_clear
.global tmi_edit_line_insert
.global tmi_edit_char_insert
.global tmi_edit_line_delete
.global tmi_edit_char_delete

.endif
